FROM ubuntu:18.04

MAINTAINER "Allan Wilson"

LABEL name="Docker build AlluHomeHub"

RUN git clone https://github.com/allanwilsonGithub/allanwilsonGithub.github.io.git

RUN cd /allanwilsonGithub.github.io/coding/alluHomeHub

#get the internal IP with ifconfig
#update package.json with internal IP